import puppeteer from "puppeteer-core";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1500, height: 950 });
await page.goto("http://localhost:1420/", { waitUntil: "networkidle0" });
await page.waitForSelector("#login-username");
await page.type("#login-username", process.env.VERIFY_USER);
await page.type("#login-password", process.env.VERIFY_PASS);
await page.keyboard.press("Enter");
await sleep(2500);
await page.evaluate(() => { [...document.querySelectorAll("button")].find(x => /^tickets$/i.test((x.textContent||"").trim()))?.click(); });
await sleep(4000);
const h3s = await page.evaluate(() => [...document.querySelectorAll("h3")].map(h => (h.textContent||"").trim()).slice(0,20));
console.log("h3 list:", JSON.stringify(h3s));
const asides = await page.evaluate(() => document.querySelectorAll("aside").length);
console.log("asides:", asides);
const tds = await page.evaluate(() => [...document.querySelectorAll("td")].slice(0,4).map(td => (td.textContent||"").trim()));
console.log("first tds:", JSON.stringify(tds));
await browser.close();
