bind 0.0.0.0
port 26379
supervised no
daemonize no
requirepass __REPLACE_WITH_RANDOM_32_BYTES__
masterauth __REPLACE_WITH_RANDOM_32_BYTES__

# Master set — three sentinels, 2 votes = quorum
sentinel monitor mymaster redis-data-0.redis-data-headless.rag-chatbot.svc.cluster.local 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
sentinel resolve-hostnames yes
sentinel auth-pass mymaster __REPLACE_WITH_RANDOM_32_BYTES__
